name: trinity
description: Trinity Pulse Engine â€“ Heartbeat â†’ Audio
publish_to: 'none'
version: 0.9.1+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  sensors_plus: ^5.0.0
  just_audio: ^0.9.38

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/pulse/trinity_pulse.wav
